### ISSUE TITLE
Machine::IsBootstrapped will wait indefinitely if "kubeadm init" fails

### ISSUE THREAD

**Issue by isaacdorfman** [kubernetes-sigs/cluster-api-provider-kubevirt#107]
The command to run in cloud-init is "kubeadm init --config /run/kubeadm/kubeadm.yaml  && echo success > /run/cluster-api/bootstrap-success.complete'" and Machine::IsBootstrapped waits for the existence of /run/cluster-api/bootstrap-success.complete.
If kubeadm init exits with error the cluster creation will be stuck.

**Comment by davidvossel** [comment]
i believe the Machine Health Check (MHC) would be helpful here for timing out machines which never successfully bootstrap. 

As an optimization, we could request that the kubeadm bootstrapper gives us an indication that kubeadm init has failed, which we can interpret
