### ISSUE TITLE
KubeVirtMachine uses VMI instead of VM

### ISSUE THREAD

**Issue by davidvossel** [kubernetes-sigs/cluster-api-provider-kubevirt#11]
Hey,

First off, It's really great to see this provider land! Excellent work!

One thing stuck out to me while I was looking through this that would be good to talk though. Right now the KubeVirtMachine api uses a VMI spec rather than a VM spec and that VMI spec is later on used to create a persistent VM. By starting with a VMI spec rather than a VM spec, we lose the ability to exercise some the persistent storage workflows provided by the VM spec's DataVolumeTemplates.

How would you all feel about transitioning the KubeVirtMachine api to reference a VM spec instead of a VMI spec? That would allow us to describe both the VMI and how the storage is provided for the VMI using DataVolumeTemplates. 

To leverage the VM spec, there's a trick we'd need to implement to make this work correctly. The names of the DataVolumes referenced in the VM spec's DataVolumeTemplate section would need to have something unique appended to them for each unique VM created from the KubeVirtMachine.

sound possible?

**Comment by agradouski** [comment]
+1 sounds like a great idea @davidvossel. we went with VMI spec to keep it simple in the initial implementation, it can now be enhanced per your proposal.

**Comment by cchengleo** [comment]
+1 to this proposal! I should plan to implement this feature.
