### ISSUE TITLE
Publish arm64 images for the capk-manager

### ISSUE THREAD

**Issue by jbpratt** [kubernetes-sigs/cluster-api-provider-kubevirt#142]
When downloading the current release and installing it (https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/releases/download/v0.1.0-rc.0/infrastructure-components.yaml), the manager container goes into `CrashLoopBackOff` due to `exec /manager: exec format error` on an ARM64 cluster. It seems that there is only the amd64 image available on Quay (`quay.io/capk/capk-manager-amd64`). It looks like there is already automation in place for this but I can't find the resulting artifacts and the manifest is set to pull the amd64 image. https://github.com/kubevirt/kubevirt/issues/3558

https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/4c4743db82f5e5ed3a74a1e807a5db9d3b5e33d2/Makefile#L61
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/4c4743db82f5e5ed3a74a1e807a5db9d3b5e33d2/Makefile#L201-L203

```
  Normal   Scheduled    57s                default-scheduler  Successfully assigned capk-system/capk-controller-manager-8b94f79db-gf94l to majora
  Normal   Pulled       52s                kubelet            Successfully pulled image "quay.io/capk/capk-manager-amd64:v0.1.0-rc.0" in 3.585999603s
  Normal   Pulling      51s                kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
  Normal   Pulled       48s                kubelet            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" in 3.028312891s
  Normal   Created      48s                kubelet            Created container kube-rbac-proxy
  Normal   Started      48s                kubelet            Started container kube-rbac-proxy
  Normal   Pulled       47s                kubelet            Successfully pulled image "quay.io/capk/capk-manager-amd64:v0.1.0-rc.0" in 447.556578ms
  Normal   Pulling      26s (x3 over 55s)  kubelet            Pulling image "quay.io/capk/capk-manager-amd64:v0.1.0-rc.0"
  Normal   Created      26s (x3 over 51s)  kubelet            Created container manager
  Normal   Pulled       26s                kubelet            Successfully pulled image "quay.io/capk/capk-manager-amd64:v0.1.0-rc.0" in 448.153154ms
  Normal   Started      25s (x3 over 51s)  kubelet            Started container manager
  Warning  BackOff      17s (x7 over 46s)  kubelet            Back-off restarting failed container
```

**Comment by davidvossel** [comment]
Are you able to build/push arm64 images using our existing build system? If so what was involved?

From our end, we can update the github action that builds and pushes images to include the arm64 image. It would be helpful to have you run through the steps of building/pushing the image to a repo you control and confirming that it works for you first though.

**Comment by jbpratt** [comment]
Hey @davidvossel, sorry for not getting back to this. There are already targets for building the images and the manifest:

https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/43916429f4417c3b18ded7052768e5fb4265c0a6/Makefile#L217-L225

I think we can do the [basic qemu setup](https://github.com/docker/setup-qemu-action/#usage) in the action then just change the target being ran here:

https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/43916429f4417c3b18ded7052768e5fb4265c0a6/.github/workflows/image_build.yaml#L11-L20

I can try to fix this up myself this and send a PR, seems straight forward.
