### ISSUE TITLE
Consider switching to kubevirt.io/api from kubevirt.io/client-go

### ISSUE THREAD

**Issue by rmohr** [kubernetes-sigs/cluster-api-provider-kubevirt#16]
/kind enhancement

**What happened**:

kubevirt.io/client-go pulls in tons of dependencies and makes it hard to integrate with other kubernetes related golang packages.

**What you expected to happen**:

Starting with 0.48 we will have tagged releases of just our APIs at https://github.com/kubevirt/api and https://github.com/kubevirt/containerized-data-importer-api which can be used like described at https://github.com/kubevirt/kubevirt/blob/f4ff1cabebfd98f1f7c72bc1b1c5ab15fd6b3457/staging/src/kubevirt.io/api/README.md.

This pulls in drastically less dependencies and will make dependency resolution in the future much simpler for you.

**Comment by cchengleo** [comment]
The dependency reduction saves tons of effort on managing dependencies! We do have difficulty keeping up with the cluster-api repo due to dependency conflicting issues.
