### ISSUE TITLE
Node update with provider ID should not block KubevirtMachine status ready

### ISSUE THREAD

**Issue by nirarg** [kubernetes-sigs/cluster-api-provider-kubevirt#18]
**What happened:**
Currently the node is updated with the provider ID in the kubevirtMachine reconciler
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/83c693883aa96d7e1822b8d25166cdc6ffa5fdae/controllers/kubevirtmachine_controller.go#L296
It cause to the following behavior: as long as the node is not created, the KubevirtMachine state isn't changed to READY

**What did you expect to happen:**
The Node update should not block the KubevirtMachine Ready status

**Anything else you would like to add:**
In Openshift case, it cause to deadlock situation, because of the following conditions:
1. Node can be created only if the relevant certificate is approved
2. Certificate can be approved only if the relevant KubevirtMachine state is READY

**Comment by agradouski** [comment]
hi @nirarg -- I'm somewhat confused by this issue. To me, the underlying kubevirtmachine being in READY state is a prerequisite for the node being created. Thus, the logic is currently sequential, and both take place in machine reconciler. 

for openshift case, namely,
```
1. Node can be created only if the relevant certificate is approved
2. Certificate can be approved only if the relevant KubevirtMachine state is READY
```
why can't both still take place in machine reconciler, but we just mark kubevirtmachine ready right after successful VMI creation (and exit the loop), and place a condition (also in the machine reconciler) specifically for kubevirtmachine is ready, to then patch the node on subsequent reconcile iteration (pending by cert approval)?

we can also introduce a new intermediate state to split the two, perhaps? wdyt?

**Comment by nirarg** [comment]
Hi @agradouski 
Sorry for the confusion

As you see in the PR, current solution suggestion is to keep the Node update in the reconciler
As this is a workarround (Node update should happen in `KubevirtCloudProvider`), it doesn't make scence to me that the Node update should block the KubevirtMachine readiness
