### ISSUE TITLE
Add documents for PCI passthrough

### ISSUE THREAD

**Issue by h1r0mu** [kubernetes-sigs/cluster-api-provider-kubevirt#192]
Can I make a document contribution for CAPK?

Recently, I've tried to enable PCI passthrough on a cluster created by CAPK. As there are no such instructions (and also other official documents) in the CAPK repository, it took trial and error. I'd like to share our experience as a document.

Is it acceptable? and if it is where is the right place to add such documents?

thanks,

**Comment by davidvossel** [comment]
yes, absolutely! make a pr in the `docs/` dir

**Comment by agradouski** [comment]
thank you for your contribution @h1r0mu - this might be very useful for others
