### ISSUE TITLE
KubevirtMachineTemplate VMs with our default ubuntu images have no console logs

### ISSUE THREAD

**Issue by hh** [kubernetes-sigs/cluster-api-provider-kubevirt#197]
**What steps did you take and what happened:**

We used the ubuntu-2004 images generated from  [our-image-creation-process.md](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/a6326da5345df60d33eb0244cd904a76c141b994/docs/our-image-creation-process.md) as in a `KubeVirtMachineTemplate` [here](https://github.com/sharingio/coder/blob/49dfe18848ee6c2eb85b312c24d1abe727fad239/examples/templates/kubevirt/kv1.yaml#L61-L64) 

**What did you expect to happen:**

Be able to view the output via: `virtctl console VM`
However no logs appear.

**Anything else you would like to add:**

It seems the default serial console tty is `ttyS0`, however at least our ubuntu images do not seem to be configured to log to console. I may be missing something, but by default ubuntu does no logging to console, and I do not see us doing anything an image-build time or vm-creation time to modify the necessary kernel argument for `console=ttyS0`

**Environment:**

- Cluster-api version: v1.2.3 
- Cluster-api-provider-kubevirt version: v0.1.2
- Kubernetes version: v1.23.5 
- KubeVirt version: v0.58.0

/kind bug

**Comment by qinqon** [comment]
Latest Ubuntu image we use a kubevirtci at capk has console, they are build from https://github.com/kubernetes-sigs/image-builder/pull/984

**Comment by hh** [comment]
Not sure if my comment on the closed #186 would notify folks, so pulling into this open issue: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/186#issuecomment-1280072067

I can see the image was pushed here: https://quay.io/repository/capk/ubuntu-2004-container-disk?tab=tags&tag=latest

Are there other locations / type of images?
Is there a documented release process for these images?

**Comment by hh** [comment]
ie. Do we push qcow or other images?

**Comment by qinqon** [comment]
This is the docs capk has to build images: 
- https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/main/docs/our-image-creation-process.md

Right now there is no automation to push image changes.
