### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by galbeniluz** [kubernetes-sigs/cluster-api-provider-kubevirt#205]
Hi, does this provider supports other images than the ubuntu container image? like CentOS qcow2 images ? does it support KubeVirt CDI?

**Comment by davidvossel** [comment]
>Hi, does this provider supports other images than the ubuntu container image? like CentOS qcow2 images ?

We're currently only building community images for ubuntu, but we certainly aren't limited to ubuntu. The image creation project for building capk images is found here, https://github.com/kubernetes-sigs/image-builder 

Image-build supports a few different variants, such as rocky linux, rhel, centos, and ubuntu. You can roll out your own images for capk by running something like `make build-kubevirt-qemu-ubuntu-2004` within the images/capi directory of the image-builder repo.

**Comment by davidvossel** [comment]
> does it support KubeVirt CDI?

also, yes. we do support cdi with capk for persistent VMs.
