### ISSUE TITLE
Cannot change LB service namespace when infraClusterSecretRef is used (kubeconfig by default)

### ISSUE THREAD

**Issue by aamoyel** [kubernetes-sigs/cluster-api-provider-kubevirt#219]
**What steps did you take and what happened:**
When we use a "remote" cluster-api cluster to bootstrap virtual machines on an external kubevirt cluster, we currently used infraClusterSecretRef to provide a kubeconfig file to the controller.
Actually, we can bootstrap clusters VMs in specific namespaces but LoadBalancer, NodePort or ClusterIP services are currently created in the namespace specified in the kubeconfig (or default if not set). With this implementation, kubeconfig are not reusable for multiple clusters in multiple namespaces and Services cannot make calls to control-plane api-server pods from default namespace.

**What did you expect to happen:**
Like labels and annotations in controlPlaneServiceTemplate.metadata Object, i think it would be great to use the namespace provided in metadata to create the service in a selected namespace.

Here is the CRD currently maintained:
![image](https://user-images.githubusercontent.com/73712310/214596915-ac54e9a8-aa3d-4baf-bc7f-5f57ac5eb6bc.png)

**Environment:**

- Cluster-api version: v1.3.2
- Cluster-api-provider-kubevirt version: v0.1.4
- Kubernetes version: (use `kubectl version`): v1.26.1
- KubeVirt version: v0.58.0
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1

/kind bug

**Comment by BarthV** [comment]
gentle bump :)

**Comment by cchengleo** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/220

**Comment by aamoyel** [comment]
EasyCLA works in #228, sorry for my miss, my commit email was not the same as the easycla form.
