### ISSUE TITLE
clusterctl init failed

### ISSUE THREAD

**Issue by iming0319** [kubernetes-sigs/cluster-api-provider-kubevirt#223]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
by standard cluster init command
$ clusterctl init --infrastructure kubevirt
I met error message
Error: failed to get provider components for the "kubevirt" provider: failed to read "infrastructure-components.yaml" from provider's repository "infrastructure-kubevirt": failed to get GitHub release v0.1.5: failed to read release "v0.1.5": GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-kubevirt/releases/tags/v0.1.5: 404 Not Found []

**What did you expect to happen:**
message "Your management cluster has been initialized successfully"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This is because the latest release is 0.1.5
but git hub release stays in 0.1.4
**Just release 0.1.5, especially the file "infrastructure-components.yaml"!**

**Environment:**

- Cluster-api version: 
- Cluster-api-provider-kubevirt version: 
- Kubernetes version: (use `kubectl version`): 
- KubeVirt version:
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

**Comment by cchengleo** [comment]
There is some issue when cutting the release for 0.1.5. Could you try 0.1.6?
