### ISSUE TITLE
What means KubeVirt?

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/cluster-api-provider-kubevirt#243]
**What steps did you take and what happened:**

I read the README

**What did you expect to happen:**

I expected to understand what KubeVirt means

**Anything else you would like to add:**

Please explain what kind of tools KubeVirt uses.

Does this provider build upon KubeVirt, so that you need KubeVirt first, or does your provider uses libVirt,
to provide KubeVirt?

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

**Comment by davidvossel** [comment]
hey, that information is in our quickstart here, https://cluster-api.sigs.k8s.io/user/quick-start.html#install-kubevirt-on-the-kind-cluster

KubeVirt is a requirement for capk. KubeVirt is the virtualization platform for kubernetes. see kubevirt.io and https://github.com/kubevirt/kubevirt for more information.

**Comment by guettli** [comment]
@davidvossel you can mention this:

> KubeVirt is a requirement for capk. KubeVirt is the virtualization platform for kubernetes.
