### ISSUE TITLE
KubeVirt v1.0.0 Support

### ISSUE THREAD

**Issue by gunine** [kubernetes-sigs/cluster-api-provider-kubevirt#263]
**What steps did you take and what happened:**
The current implementation of capk, only supports kubevirt up to v0.58.0.

**What did you expect to happen:**
Since kubevirt v1.0.0 became GA, it would be great that capk can officially support kubevirt v1.0.

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api version: 1.4.4
- Cluster-api-provider-kubevirt version: master
- Kubernetes version: (use `kubectl version`): v1.27.5
- KubeVirt version: v1.0.0
- OS (e.g. from `/etc/os-release`): 
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

**Comment by gunine** [comment]
Since kubevirt 1.1.0 was just released. It would be great that capk also supports kubevirt 1.1.0.

**Comment by bzub** [comment]
In my testing it seems that `v0.1.8` of this provider works well with the latest cluster-api components as well as kubevirt `v1.1.0`. Is this issue still needed?

**Comment by gunine** [comment]
Yes, the majority of the features work well except newly added features such as (cpu) architecture and so on. The kubevirt dependencies need to be bumped up accordingly.

**Comment by gunine** [comment]
Since the 0.1.8 officially supports kubevirt 1.0.0, I'd like to close this issue. Maybe a new issue will be generated to support kubevirt 1.1.0.
