### ISSUE TITLE
Is it possible to change the config when cluster is running , like cpu\mem?

### ISSUE THREAD

**Issue by HenryGuo1019** [kubernetes-sigs/cluster-api-provider-kubevirt#281]
For now , i can't change the kubevirtMachineTemplate when the cluster is running and i also try to change the kubevirtmachine , it return configured but did't change the VM and restart it , is there any way that can change it?

**Comment by davidvossel** [comment]
> kubevirtmachine , it return configured but did't change the VM and restart it , is there any way that can change it?

For us, machineTemplates are meant to be immutable. 

The procedure for changing the template would be to 
1. create a new template with the desired changes
2. update the MachineSet or MachineDeployment to point to the new template
3. Those controllers will then rollout the new changes.

more info can be found here, https://release-0-3.cluster-api.sigs.k8s.io/tasks/change-machine-template
