### ISSUE TITLE
Add quickstart example in README

### ISSUE THREAD

**Issue by wangxin311** [kubernetes-sigs/cluster-api-provider-kubevirt#36]
I didn't see any example on how to use the kubevirt cluster api, can we have a step by step deployment example/guide, so people who new to kubevirt cluster api can get started from there? Thanks

**Comment by sayantani11** [comment]
Yes need to have pr in cluster-api

**Comment by davidvossel** [comment]
/assign @isaacdorfman 

Isaac is working on the clusterctl integration which will allow us to create a quickstart. https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/113

**Comment by nunnatsa** [comment]
/close

solved in https://github.com/kubernetes-sigs/cluster-api/pull/7444
