### ISSUE TITLE
Add KubevirtMachine and VirtualMachine metadata to KubevirtMachineTemplate spec

### ISSUE THREAD

**Issue by pjaton** [kubernetes-sigs/cluster-api-provider-kubevirt#41]
Hi team,

Thank you for all the work on this new provider. This is great to see it land.

Following on #11, the spec of the `KubevirtMachineTemplate` to specify KubeVirt resources seems quite deep and, with the understand that this would be a backward incompatible changes, I would like to propose a flatter structure.

Currently, the structure is as follow:

```plain
KubevirtMachineTemplate
├── ...
└── spec
    └── template
        └── spec
            ├── bootstrapped
            ├── providerID
            └── vmSpec  (= VirtualMachineInstance.spec)
                ├── accessCredentials
                ├── affinity
                └── ...
```

Assuming #11 is implemented and the `VirtualMachine.spec` is used instead of the `VirtualMachineInstance.spec`, can we update the structure to something like the following:

```plain
KubevirtMachineTemplate
├── ...
└── spec
    ├── bootstrapped
    ├── providerID
    └── template
        ├── metadata
        └── spec  (= VirtualMachine.spec)
            ├── dataVolumeTemplates
            ├── runStrategy
            ├── running
            └── template
                ├── metadata
                └── spec
```

Here are my thoughts on which I based this proposal: 

* Because the `KubevirtMachineTemplate` name already describes clearly that this is a template, the first `spec.template` path might be redundant, even more as there are no other fields specified at these levels.
* `bootstrapped` and `providerID` are, as far as I understand, properties of the machine resource, so having them directly under the `spec` of the `KubevirtMachineTemplate` seems appropriate.
* The machine is provided by a KubeVirt's `VirtualMachine` so we need its template, which feels appropriate as a `spec.template` field.
* As one might want to specify labels and annotations for the `VirtualMachine`, `spec.template` should have a `metadata` field.
* The virtualMachine spec can then be under `spec.template.spec`

Any thoughts, opinions or concerns on adapting this structure in such a way?

**Comment by davidvossel** [comment]
As for flatting the KubevirtMachineTemplate, I'm unsure. By moving providerID out of the current structure, we are abandoning a consistent API convention the other capi providers use.

For example, here's providerId across AWS and AZURe providers

```awsTemplate.Spec.Template.Spec.ProviderId```
```azureTemplate.Spec.Template.Spec.ProviderId```

Today the capk provider follows this convention with...

```kvMachineTemplate.Spec.Template.Spec.ProviderId```

I'm unsure what ramifications we'd encounter later on if we flatten this to  ```kvMachineTemplate.Spec.ProviderId```. Maybe it's fine, or maybe it becomes a pain point because we do something slightly different than everyone else.

While this doesn't offer any flattening of the structure, I believe what I have below allows everything to be expressed accurately. 

```
KubevirtMachineTemplate
├── ...
└── spec
    └── template
        ├── metadata (metadata used for KubevirtMachine)
        └── spec
            ├── bootstrapped (depreciated - this just got removed already)
            ├── providerID
            └── virtualMachineTemplate
                ├── metadata (metadata used when creating the KubeVirt VM)
                └── spec  (= VirtualMachine.spec)
                    ├── dataVolumeTemplates
                    └── template
                        ├── metadata (metadata assigned to the running VMI instance)
                        └── spec  (= VirtualMachineInstance.spec)
```

**Comment by pjaton** [comment]
Thanks @davidvossel, make sense to keep this schema aligned with other provider and, as you added to your schema, this allow the addition of the `metadata` for the `KubevirtMachine`; which I didn't realize was also missing.

Renaming this issue from ***`Flattening KubevirtMachineTemplate.spec and adding metadata for VirtualMachine`*** to ***`Add KubevirtMachine and VirtualMachine metadata to KubevirtMachineTemplate spec`*** for clarity.

**Comment by davidvossel** [comment]
> Thanks @davidvossel, make sense to keep this schema aligned with other provider and, as you added to your schema, this allow the addition of the metadata for the KubevirtMachine; which I didn't realize was also missing.

excellent!

I'm disappointed with how deeply nested the yaml is with what I proposed, but I think this might just be the nature of what we're building. @rmohr it would be good to have your eyes on this as well.

**Comment by davidvossel** [comment]
is anyone actively working on this one? I don't mind picking this up if no one else is

**Comment by pjaton** [comment]
Hi @davidvossel, as far as I know, this issue is not being actively work on and it would be great if you could work on it. Thank you!
