### ISSUE TITLE
`clusterctl` describe shows stale information

### ISSUE THREAD

**Issue by cchengleo** [kubernetes-sigs/cluster-api-provider-kubevirt#56]
**What steps did you take and what happened:**

While testing #54, I noticed the status posted by `clusterctl describe` has stated information even though the tenant cluster was successfully formed:

```
$ cluster-api/bin/clusterctl --kubeconfig kubeconfig.yaml describe cluster workload-cluster -n test-dda2dda

NAME                                                                 READY  SEVERITY  REASON                       SINCE  MESSAGE
/workload-cluster                                                    True                                          57m
├─ClusterInfrastructure - KubevirtCluster/workload-cluster           True                                          60m
├─ControlPlane - KubeadmControlPlane/workload-cluster-control-plane  True                                          57m
│ └─Machine/workload-cluster-control-plane-9wn55                     True                                          57m
└─Workers
  └─MachineDeployment/workload-cluster-md-0                          False  Warning   WaitingForAvailableMachines  60m    Minimum availability requires 1 replicas, current 0 available
    └─Machine/workload-cluster-md-0-776c5bf974-x2c62                 True                                          56m 
```

**What did you expect to happen:**
There should be no warning.

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api version: `v0.4.5` == `65f95147d52abface1778dd426ad948999cbac7b`
- Cluster-api-provider-kubevirt version: `353694f61daecb3e4c4ea78d13477a2fc209a4a5`
- Kubernetes version: (use `kubectl version`): 
```Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}```
- KubeVirt version: v0.38.0
- OS (e.g. from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

/kind bug

**Comment by sayantani11** [comment]
Umm... One thing can be that you didn't mention replicas, like you need to use minimum 1 replica. Another one can be for the device that you are one, it might not have the capacity for the process. So, you might try using a cloud platform for this. Maybe just a suggestion.
