### ISSUE TITLE
Tenant cluster VMs running on external infra are not tracked after creation

### ISSUE THREAD

**Issue by agradouski** [kubernetes-sigs/cluster-api-provider-kubevirt#78]
This feature allows running tenant cluster VMs on external infrastructure (external infra meaning any cluster that is not the CAPI/CAPK management cluster itself): https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/32

One outstanding issue with tenant clusters deployed on external infra is that CAPI/CAPK management plane does not track underlying VMs for tenant clusters after creation. Meaning, if an underlying VM of a tenant cluster failed completely, or restarted with a different IP, the management plane would not be able to recover the node.

This problem is resolved for tenant clusters running on the management cluster with this PR (issue https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/70): https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/73

But we currently lack the resolution for tenant clusters running on external infra.

Please investigate.

**Comment by davidvossel** [comment]
we need to either create an informer or poll for VM changes on external clusters

**Comment by agradouski** [comment]
this issue is related to issue https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/100
