### ISSUE TITLE
Add capk image build process

### ISSUE THREAD

**Issue by nirarg** [kubernetes-sigs/cluster-api-provider-kubevirt#84]
Add capk image build process

* Triggered by Github actions
* Triggered on every PR merge (hash tag) or nightly based builds
* Image should be pushed to https://quay.io/organization/capk

Completing this task would allow us to add Quick start for capk (https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/36 and https://github.com/kubernetes-sigs/cluster-api/issues/5845)

**Comment by nirarg** [comment]
The image was added by @isaacdorfman 
PR: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/108
Still need to automate this image creation

**Comment by isaacdorfman** [comment]
I will add a comment in capk repo docs that explain how to build the image using image-builder newly created kubevirt target.
