### ISSUE TITLE
[e2e tests] Cover creating tenant clusters in external infra clusters in the integration tests

### ISSUE THREAD

**Issue by rmohr** [kubernetes-sigs/cluster-api-provider-kubevirt#90]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

We are not testing the creation of capk tenant clusters in external clusters.

**What did you expect to happen:**

Let's add an integration test which creates a kubeconfig with a service account token and corresponding RBAC rules and then uses this kubeconfig in the capk controllers to create the clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 
- Cluster-api-provider-kubevirt version: 
- Kubernetes version: (use `kubectl version`): 
- KubeVirt version:
- OS (e.g. from `/etc/os-release`):

kind enhancement
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

**Comment by rmohr** [comment]
@agradouski FYI, is that covering what you are mostly intersted in testing asap?

**Comment by agradouski** [comment]
FYI -- I'm actively working on this issue.
