### ISSUE TITLE
Documentation - goals, use cases, design decisions

### ISSUE THREAD

**Issue by mzayats** [kubernetes-sigs/cluster-api-provider-kubevirt#97]
For the sake of potential users and contributors, it would be good to have a statement on the project goals, prioritized and dismissed use cases as well as major design decisions that were made by the core team.

It will make it much easier for those who consider contributing to the project to decide whether it's going to match their needs.

**Comment by sayantani11** [comment]
+1 on this

**Comment by davidvossel** [comment]
@mzayats Is there example you can point us to for another cluster api provider that has a similar statement to what you're interested in here?
